# Project Alpha: RL Bot v63p

## 📋 TODO & Roadmap
- **Data Policy:** Should we apply `handle_zeros_as_nan` globally to all matrices?
- **Feature Scaling:** Finalize the `get_agent_view` dual-view scaling logic.
- **Performance:** Move heavy logic (`analyze_4d_regime`) into `core` modular library.

<details>
<summary><b>📜 Version History (v59 - v63)</b></summary>

### v63
- Added **Metric Registry** (Strong-typed, dual-view).
- Fixed **Index Poisoning** bug (Dates in Ticker column).
- Unified **Perception** and **Execution** in Audit packs.
- Added 4 New Pillars: Return Autocorr, Range Position, OBV Divergence, Convexity.

### v62
- Fixed **Object Reference Mutation** bug in `compute_alpha_ensemble`.
- Added `PostBuildVerifier`, `DeepDiveDebugger`, and `ForensicExporter`.

### v61
- Verified all metrics with Excel parity.
- Refactored `AlphaEngine` into Orchestrator pattern.

### v60
- Converted notebook code to modular system.
- Added Volatility Regime plots.

### v59
- Implemented **Result Pattern** for error handling.
- Switched to logarithmic returns globally.
</details>

## I. Initialization & Environment

In [1]:
# 1. Setup & Path
%load_ext autoreload
%autoreload 2

import sys
import gc
import pandas as pd
import numpy as np
from pathlib import Path
from IPython.display import display, clear_output
import plotly.io as pio

def add_project_root_to_path():
    current = Path.cwd()
    for path in [current] + list(current.parents):
        if path.name == "notebooks_RLVR":
            sys.path.insert(0, str(path))
            return path
        candidate = path / "notebooks_RLVR"
        if candidate.exists():
            sys.path.insert(0, str(candidate))
            return candidate
    raise RuntimeError("Could not find notebooks_RLVR directory")

add_project_root_to_path()

# 2. Display Settings
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)
pd.set_option("display.precision", 4)

# 3. Project Imports
from core.analyzer import create_walk_forward_analyzer, run_headless_simulation
from core.auditor import SystemAuditor as SA
from core.builder import ParallelFeatureBuilder, FeatureCubeStitcher
from core.contracts import FilterPack, EngineInput, MarketObservation
from core.engine import AlphaEngine, AlphaCache
from core.environment import DiscoveryEnv
from core.features import generate_features
from core.logic import AlphaLogic
from core.paths import OUTPUT_DIR
from core.quant import QuantUtils, TickerEngine
from core.settings import GLOBAL_SETTINGS
from core.utils import SystemUtils as SU
from strategy.registry import STRATEGY_REGISTRY

# 4. Load Environment Paths
DATA_DIR = Path(SU.load_env_from_root("DATA_DIR"))
DATA_PATH_OHLCV = Path(SU.load_env_from_root("DATA_PATH_OHLCV"))
DATA_PATH_INDICES = Path(SU.load_env_from_root("DATA_PATH_INDICES"))
print(f"✓ Paths Initialized.\nDATA Dir: {DATA_DIR}\nOHLCV: {DATA_PATH_OHLCV}\nIndices: {DATA_PATH_INDICES}")

NOTEBOOKS_RLVR_ROOT: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR

OUTPUT_DIR: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output

✓ Paths Initialized.
DATA Dir: c:\Users\ping\Files_win10\python\py311\stocks\data
OHLCV: c:\Users\ping\Files_win10\python\py311\stocks\data\df_OHLCV_stocks_etfs.parquet
Indices: c:\Users\ping\Files_win10\python\py311\stocks\data\df_indices.parquet

## II. Data Pipeline

In [2]:
# # === RELOADING FROM PARQUET ===
# features_df = pd.read_parquet("output/features_df.parquet")
# macro_df = pd.read_parquet("output/macro_df.parquet")
# df_close_wide = pd.read_parquet("output/df_close_wide.parquet")
# df_atrp_wide = pd.read_parquet("output/df_atrp_wide.parquet")
# df_trp_wide = pd.read_parquet("output/df_trp_wide.parquet")

# df_indices = pd.read_parquet(DATA_PATH_INDICES, engine="pyarrow")
# df_ohlcv = pd.read_parquet(DATA_PATH_OHLCV, engine="pyarrow")
# df_fed = pd.read_parquet(
#     DATA_DIR / "High_Yield_Spread_T10Y2Y_Spread.parquet", engine="pyarrow"
# )

In [3]:
print("⏳ Loading DataFrames... takes ~6 minutes")
df_indices = pd.read_parquet(DATA_PATH_INDICES, engine="pyarrow")
df_ohlcv = pd.read_parquet(DATA_PATH_OHLCV, engine="pyarrow")
df_fed = pd.read_parquet(
    DATA_DIR / "High_Yield_Spread_T10Y2Y_Spread.parquet", engine="pyarrow"
)

print("⚡ Generating Features...")
features_df, macro_df = generate_features(
    df_ohlcv=df_ohlcv,
    df_indices=df_indices,
    df_fed=df_fed,
    benchmark_ticker=GLOBAL_SETTINGS["benchmark_ticker"],
)

print("🚀 Unstacking Wide Matrices...")
df_close_wide = df_ohlcv["Adj Close"].unstack(level=0)
df_atrp_wide = features_df["ATRP"].unstack(level=0).reindex_like(df_close_wide)
df_trp_wide = features_df["TRP"].unstack(level=0).reindex_like(df_close_wide)

if GLOBAL_SETTINGS["handle_zeros_as_nan"]:
    df_close_wide = df_close_wide.replace(0, np.nan)

df_close_wide = df_close_wide.ffill(limit=GLOBAL_SETTINGS["max_data_gap_ffill"])
df_close_wide = df_close_wide.fillna(GLOBAL_SETTINGS["nan_price_replacement"])

print(
    f"✅ Pipeline Complete. Tickers: {len(df_close_wide.columns)}, Days: {len(df_close_wide)}"
)

⏳ Loading DataFrames... takes ~6 minutes
⚡ Generating Features...
⚡ Generating Decoupled Features (Benchmark: SPY)...
🚀 Unstacking Wide Matrices...
✅ Pipeline Complete. Tickers: 1576, Days: 8426

In [4]:
# === SAVE TO PERSISTENCE SANDBOX ===
_fn = OUTPUT_DIR / "features_df.parquet"
features_df.to_parquet(_fn, engine="pyarrow", index=True)
print(f"Saved: {_fn}")

_fn = OUTPUT_DIR / "macro_df.parquet"
macro_df.to_parquet(_fn, engine="pyarrow", index=True)
print(f"Saved: {_fn}")

_fn = OUTPUT_DIR / "df_close_wide.parquet"
df_close_wide.to_parquet(_fn, engine="pyarrow", index=True)
print(f"Saved: {_fn}")

_fn = OUTPUT_DIR / "df_atrp_wide.parquet"
df_atrp_wide.to_parquet(_fn, engine="pyarrow", index=True)
print(f"Saved: {_fn}")

_fn = OUTPUT_DIR / "df_trp_wide.parquet"
df_trp_wide.to_parquet(_fn, engine="pyarrow", index=True)
print(f"Saved: {_fn}")

Saved: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\features_df.parquet
Saved: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\macro_df.parquet
Saved: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\df_close_wide.parquet
Saved: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\df_atrp_wide.parquet
Saved: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\df_trp_wide.parquet

## III. The Analysis Suite

In [5]:
# SINGLE SOURCE OF TRUTH
engine = AlphaEngine(
    df_ohlcv=df_ohlcv,
    features_df=features_df,
    macro_df=macro_df,
    df_close_wide=df_close_wide,
    df_atrp_wide=df_atrp_wide,
    df_trp_wide=df_trp_wide,
)
print("🎯 Master AlphaEngine Ready.")

🎯 Master AlphaEngine Ready.

In [6]:
# Configuration for Interactive UI
_inputs = EngineInput(
    mode="Ranking",
    decision_date=pd.Timestamp("2026-04-16"),
    lookback_period=189,
    holding_period=5,
    metric="Sharpe (TRP)",
    benchmark_ticker=GLOBAL_SETTINGS["benchmark_ticker"],
    rank_start=1,
    rank_end=200,
    debug=False,
)

analyzer1, stage1_pack = create_walk_forward_analyzer(
    engine, _inputs, universe_subset=None
)
analyzer1.show()

DEBUG: 938 stocks passed filters on 2026-04-16

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [7]:
print("--- CASCADE FILTER, TICKERS PASSED FIRST FILTER ---")
# Get decision date from last run
decision_date_last_run = FilterPack(decision_date=analyzer1.last_run.decision_date)

# 1. LAUNCH STAGE 2 (Cascade)
# universe_subset=analyzer1.last_run.tickers means "Scan the whole market"
analyzer2, stage2_pack = create_walk_forward_analyzer(
    engine,
    universe_subset=analyzer1.last_run.tickers,
    # universe_subset=None,
    filter_pack=decision_date_last_run,
)

print("🚀 Ready for Stage 2: Run Simulation for 2nd filter.")
analyzer2.show()

--- CASCADE FILTER, TICKERS PASSED FIRST FILTER ---
🚀 Ready for Stage 2: Run Simulation for 2nd filter.

VBox(children=(HTML(value='<b>1. Timeline Configuration:</b> (Past <--- Decision ---> Future)'), HBox(children…

In [8]:
# Configuration for Interactive UI
_inputs = EngineInput(
    mode="Ranking",
    decision_date=pd.Timestamp("2026-04-16"),
    lookback_period=10,
    holding_period=5,
    metric="Log Price Gain",
    benchmark_ticker=GLOBAL_SETTINGS["benchmark_ticker"],
    rank_start=1,
    rank_end=3,
    debug=False,
)

print("--- 🤖 RL AGENT HEADLESS VIEW ---")
metrics_df = run_headless_simulation(engine, _inputs)
display(metrics_df)
print(f"\nTarget Reward Signal: {metrics_df.loc['Group Gain', 'Holding']:.6f}")

--- 🤖 RL AGENT HEADLESS VIEW ---
DEBUG: 938 stocks passed filters on 2026-04-16
----------------------------------------------------------------------
Timeline: [2026-04-01] -> Decision: 2026-04-16 -> Entry: 2026-04-17 -> End: 2026-04-24
Selected Tickers (3):
SOXL, CRDO, NBIS
----------------------------------------------------------------------

                            Full  Lookback  Holding
Metric
Group Gain                0.6818    0.5047   0.1557
Benchmark Gain            0.0858    0.0684   0.0053
== Gain Delta             0.5960    0.4363   0.1504
Group Sharpe             23.1077   24.1712  38.7616
Benchmark Sharpe         10.9495   14.0962   2.3401
== Sharpe Delta          12.1582   10.0750  36.4215
Group Sharpe (ATRP)       0.6272    0.6934   0.5230
Benchmark Sharpe (ATRP)   0.3892    0.4683   0.0879
== Sharpe (ATRP) Delta    0.2380    0.2251   0.4351
Group Sharpe (TRP)        0.5379    0.6064   0.4259
Benchmark Sharpe (TRP)    0.4575    0.5607   0.1070
== Sharpe (TRP) Delta     0.0804    0.0457   0.3190

Target Reward Signal: 0.155737

In [9]:
##################################
##################################
##################################

In [10]:
result = SU.visualize_analyzer_structure(analyzer=analyzer1)

====================================================================
🔍 HIGH-TRANSPARENCY AUDIT MAP
====================================================================
[  0] 📦 audit_pack (EngineOutput)
[  1]   📈 portfolio_series (shape=(196,))
[  2]   📈 benchmark_series (shape=(196,))
[  3]   🧮 normalized_plot_data (shape=(196, 200))
[  4]   📂 tickers (len=200)
[  5]     📄 index_0 (str)
[  6]     📄 index_1 (str)
[  7]     📄 index_2 (str)
[  8]     📄 index_3 (str)
[  9]     📄 index_4 (str)
[ 10]     📄 index_5 (str)
[ 11]     📄 index_6 (str)
[ 12]     📄 index_7 (str)
[ 13]     📄 index_8 (str)
[ 14]     📄 index_9 (str)
[ 15]     📄 index_10 (str)
[ 16]     📄 index_11 (str)
[ 17]     📄 index_12 (str)
[ 18]     📄 index_13 (str)
[ 19]     📄 index_14 (str)
[ 20]     📄 index_15 (str)
[ 21]     📄 index_16 (str)
[ 22]     📄 index_17 (str)
[ 23]     📄 index_18 (str)
[ 24]     📄 index_19 (str)
[ 25]     📄 index_20 (str)
[ 26]     📄 index_21 (str)
[ 27]     📄 index_22 (str)
[ 28]     📄 index_23 (str)
[ 29]     📄 index_24 (str)
[ 30]     📄 index_25 (str)
[ 31]     📄 index_26 (str)
[ 32]     📄 index_27 (str)
[ 33]     📄 index_28 (str)
[ 34]     📄 index_29 (str)
[ 35]     📄 index_30 (str)
[ 36]     📄 index_31 (str)
[ 37]     📄 index_32 (str)
[ 38]     📄 index_33 (str)
[ 39]     📄 index_34 (str)
[ 40]     📄 index_35 (str)
[ 41]     📄 index_36 (str)
[ 42]     📄 index_37 (str)
[ 43]     📄 index_38 (str)
[ 44]     📄 index_39 (str)
[ 45]     📄 index_40 (str)
[ 46]     📄 index_41 (str)
[ 47]     📄 index_42 (str)
[ 48]     📄 index_43 (str)
[ 49]     📄 index_44 (str)
[ 50]     📄 index_45 (str)
[ 51]     📄 index_46 (str)
[ 52]     📄 index_47 (str)
[ 53]     📄 index_48 (str)
[ 54]     📄 index_49 (str)
[ 55]     📄 index_50 (str)
[ 56]     📄 index_51 (str)
[ 57]     📄 index_52 (str)
[ 58]     📄 index_53 (str)
[ 59]     📄 index_54 (str)
[ 60]     📄 index_55 (str)
[ 61]     📄 index_56 (str)
[ 62]     📄 index_57 (str)
[ 63]     📄 index_58 (str)
[ 64]     📄 index_59 (str)
[ 65]     📄 index_60 (str)
[ 66]     📄 index_61 (str)
[ 67]     📄 index_62 (str)
[ 68]     📄 index_63 (str)
[ 69]     📄 index_64 (str)
[ 70]     📄 index_65 (str)
[ 71]     📄 index_66 (str)
[ 72]     📄 index_67 (str)
[ 73]     📄 index_68 (str)
[ 74]     📄 index_69 (str)
[ 75]     📄 index_70 (str)
[ 76]     📄 index_71 (str)
[ 77]     📄 index_72 (str)
[ 78]     📄 index_73 (str)
[ 79]     📄 index_74 (str)
[ 80]     📄 index_75 (str)
[ 81]     📄 index_76 (str)
[ 82]     📄 index_77 (str)
[ 83]     📄 index_78 (str)
[ 84]     📄 index_79 (str)
[ 85]     📄 index_80 (str)
[ 86]     📄 index_81 (str)
[ 87]     📄 index_82 (str)
[ 88]     📄 index_83 (str)
[ 89]     📄 index_84 (str)
[ 90]     📄 index_85 (str)
[ 91]     📄 index_86 (str)
[ 92]     📄 index_87 (str)
[ 93]     📄 index_88 (str)
[ 94]     📄 index_89 (str)
[ 95]     📄 index_90 (str)
[ 96]     📄 index_91 (str)
[ 97]     📄 index_92 (str)
[ 98]     📄 index_93 (str)
[ 99]     📄 index_94 (str)
[100]     📄 index_95 (str)
[101]     📄 index_96 (str)
[102]     📄 index_97 (str)
[103]     📄 index_98 (str)
[104]     📄 index_99 (str)
[105]     📄 index_100 (str)
[106]     📄 index_101 (str)
[107]     📄 index_102 (str)
[108]     📄 index_103 (str)
[109]     📄 index_104 (str)
[110]     📄 index_105 (str)
[111]     📄 index_106 (str)
[112]     📄 index_107 (str)
[113]     📄 index_108 (str)
[114]     📄 index_109 (str)
[115]     📄 index_110 (str)
[116]     📄 index_111 (str)
[117]     📄 index_112 (str)
[118]     📄 index_113 (str)
[119]     📄 index_114 (str)
[120]     📄 index_115 (str)
[121]     📄 index_116 (str)
[122]     📄 index_117 (str)
[123]     📄 index_118 (str)
[124]     📄 index_119 (str)
[125]     📄 index_120 (str)
[126]     📄 index_121 (str)
[127]     📄 index_122 (str)
[128]     📄 index_123 (str)
[129]     📄 index_124 (str)
[130]     📄 index_125 (str)
[131]     📄 index_126 (str)
[132]     📄 index_127 (str)
[133]     📄 index_128 (str)
[134]     📄 index_129 (str)
[135]     📄 index_130 (str)
[136]     📄 index_131 (str)
[137]     📄 index_132 (str)
[138]     📄 index_133 (str)
[139]     📄 index_134 (str)
[140]     📄 index_135 (str)
[141]     📄 index_136 (str)
[142]     📄 index_137 (str)
[143]     📄 index_138 (str)
[144]     📄 index_139 (str)
[145]     📄 index_140 (str)
[146]     📄 index_141 (str)
[147]     📄 index_142 (str)
[148]     📄 index_143 (str)
[149]     📄 index_144 (str)
[150]     📄 index_145 (str)
[151]     📄 index_146 (str)
[152]     📄 index_147 (str)
[153]     📄 index_148 (str)
[154]     📄 index_149 (str)
[155]     📄 index_150 (str)
[156]     📄 index_151 (str)
[157]     📄 index_152 (str)
[158]     📄 index_153 (str)
[159]     📄 index_154 (str)
[160]     📄 index_155 (str)
[161]     📄 index_156 (str)
[162]     📄 index_157 (str)
[163]     📄 index_158 (str)
[164]     📄 index_159 (str)
[165]     📄 index_160 (str)
[166]     📄 index_161 (str)
[167]     📄 index_162 (str)
[168]     📄 index_163 (str)
[169]     📄 index_164 (str)
[170]     📄 index_165 (str)
[171]     📄 index_166 (str)
[172]     📄 index_167 (str)
[173]     📄 index_168 (str)
[174]     📄 index_169 (str)
[175]     📄 index_170 (str)
[176]     📄 index_171 (str)
[177]     📄 index_172 (str)
[178]     📄 index_173 (str)
[179]     📄 index_174 (str)
[180]     📄 index_175 (str)
[181]     📄 index_176 (str)
[182]     📄 index_177 (str)
[183]     📄 index_178 (str)
[184]     📄 index_179 (str)
[185]     📄 index_180 (str)
[186]     📄 index_181 (str)
[187]     📄 index_182 (str)
[188]     📄 index_183 (str)
[189]     📄 index_184 (str)
[190]     📄 index_185 (str)
[191]     📄 index_186 (str)
[192]     📄 index_187 (str)
[193]     📄 index_188 (str)
[194]     📄 index_189 (str)
[195]     📄 index_190 (str)
[196]     📄 index_191 (str)
[197]     📄 index_192 (str)
[198]     📄 index_193 (str)
[199]     📄 index_194 (str)
[200]     📄 index_195 (str)
[201]     📄 index_196 (str)
[202]     📄 index_197 (str)
[203]     📄 index_198 (str)
[204]     📄 index_199 (str)
[205]   📈 initial_weights (shape=(200,))
[206]   📂 perf_metrics (len=24)
[207]     🔢 full_p_gain (float)
[208]     🔢 full_p_sharpe (float)
[209]     🔢 full_p_sharpe_atrp (float)
[210]     🔢 full_p_sharpe_trp (float)
[211]     🔢 lookback_p_gain (float)
[212]     🔢 lookback_p_sharpe (float)
[213]     🔢 lookback_p_sharpe_atrp (float)
[214]     🔢 lookback_p_sharpe_trp (float)
[215]     🔢 holding_p_gain (float)
[216]     🔢 holding_p_sharpe (float)
[217]     🔢 holding_p_sharpe_atrp (float)
[218]     🔢 holding_p_sharpe_trp (float)
[219]     🔢 full_b_gain (float)
[220]     🔢 full_b_sharpe (float)
[221]     🔢 full_b_sharpe_atrp (float)
[222]     🔢 full_b_sharpe_trp (float)
[223]     🔢 lookback_b_gain (float)
[224]     🔢 lookback_b_sharpe (float)
[225]     🔢 lookback_b_sharpe_atrp (float)
[226]     🔢 lookback_b_sharpe_trp (float)
[227]     🔢 holding_b_gain (float)
[228]     🔢 holding_b_sharpe (float)
[229]     🔢 holding_b_sharpe_atrp (float)
[230]     🔢 holding_b_sharpe_trp (float)
[231]   🧮 results_df (shape=(200, 2))
[232]   📅 start_date (Timestamp)
[233]   📅 decision_date (Timestamp)
[234]   📅 buy_date (Timestamp)
[235]   📅 holding_end_date (Timestamp)
[236]   📈 portfolio_atrp_series (shape=(196,))
[237]   📈 benchmark_atrp_series (shape=(196,))
[238]   📈 portfolio_trp_series (shape=(196,))
[239]   📈 benchmark_trp_series (shape=(196,))
[240]   📄 error_msg (NoneType)
[241]   📂 debug_data (len=9)
[242]     📂 audit_liquidity (len=6)
                ╰── date --> [See ID 233]
[243]       🔢 total_tickers_available (int)
[244]       🔢 percentile_setting (float)
[245]       🔢 final_cutoff_usd (shape=())
[246]       📄 tickers_passed (shape=())
[247]       🧮 universe_snapshot (shape=(1573, 19))
[248]     🧮 full_universe_ranking (shape=(938, 16))
[249]     📂 meta (len=4)
[250]       🔢 dropped_count (int)
[251]       📂 dropped_tickers (len=0)
[252]       🔢 clean_count (int)
[253]       📄 selection_range (str)
[254]     📦 inputs_snapshot (EngineInput)
[255]       📄 mode (str)
[256]       📅 decision_date (Timestamp)
[257]       🔢 lookback_period (int)
[258]       🔢 holding_period (int)
[259]       📄 metric (str)
[260]       📄 benchmark_ticker (str)
[261]       🔢 rank_start (int)
[262]       🔢 rank_end (int)
[263]       📂 quality_thresholds (len=4)
[264]         🔢 min_median_dollar_volume (int)
[265]         🔢 min_liquidity_percentile (float)
[266]         🔢 max_stale_pct (float)
[267]         🔢 max_same_vol_count (int)
[268]       📂 manual_tickers (len=0)
[269]       🔢 debug (bool)
[270]       📄 universe_subset (NoneType)
[271]     🧮 alpha_perception (shape=(938, 11))
[272]     📂 verification (len=2)
[273]       📂 p (len=4)
                  ╰── val --> [See ID 1]
[274]         📈 ret (shape=(196,))
                  ╰── atrp --> [See ID 236]
                  ╰── trp --> [See ID 238]
[275]       📂 b (len=4)
                  ╰── val --> [See ID 2]
[276]         📈 ret (shape=(196,))
                  ╰── atrp --> [See ID 237]
                  ╰── trp --> [See ID 239]
[277]     📂 portfolio_raw_components (len=4)
[278]       🧮 prices (shape=(196, 200))
[279]       🧮 atrp (shape=(196, 200))
[280]       🧮 trp (shape=(196, 200))
[281]       🧮 ohlcv_raw (shape=(39200, 5))
[282]     📂 benchmark_raw_components (len=4)
[283]       🧮 prices (shape=(196, 1))
[284]       🧮 atrp (shape=(196, 1))
[285]       🧮 trp (shape=(196, 1))
[286]       🧮 ohlcv_raw (shape=(196, 5))
              ╰── selection_audit --> [See ID 248]
[287]   🧮 macro_df (shape=(8426, 11))
[288]   📄 alpha_perception (NoneType)

In [11]:
target_tickers = SU.peek(4, result)

 ============================================================
 📍 INDEX: [4]
 🏷️  NAME:  tickers
 📂 PATH:  audit_pack -> tickers
 ============================================================

['SGOV',
 'SHV',
 'BIL',
 'MINT',
 'USFR',
 'BOXX',
 'PULS',
 'JPST',
 'GTLS',
 'SNDK',
 'JAAA',
 'RVMD',
 'CIEN',
 'TER',
 'EA',
 'LITE',
 'ASX',
 'VGSH',
 'WDC',
 'GLW',
 'ROIV',
 'SHY',
 'ROST',
 'EWY',
 'WBD',
 'VALE',
 'MU',
 'FTI',
 'ERIC',
 'RIO',
 'VTEB',
 'BE',
 'KEYS',
 'NOK',
 'STX',
 'FIX',
 'UTHR',
 'VCSH',
 'IGSB',
 'MUB',
 'CHRW',
 'EMXC',
 'LRCX',
 'GOOGL',
 'GOOG',
 'HSBC',
 'INTC',
 'TEVA',
 'JNJ',
 'TD',
 'CAT',
 'EWZ',
 'ALB',
 'MKSI',
 'CMI',
 'BNS',
 'BSV',
 'COPX',
 'RY',
 'SU',
 'PBR',
 'EFV',
 'ASML',
 'GSK',
 'EWT',
 'FDX',
 'ONTO',
 'BP',
 'AA',
 'IAG',
 'CVE',
 'SLV',
 'HL',
 'KGC',
 'ITUB',
 'COHR',
 'BHP',
 'AU',
 'JAZZ',
 'IAUM',
 'AMAT',
 'GLDM',
 'SGOL',
 'IAU',
 'APA',
 'B',
 'AZN',
 'XBI',
 'SCCO',
 'EMB',
 'PSLV',
 'EQX',
 'SOXX',
 'SCHF',
 'GLD',
 'VEA',
 'BG',
 'SPDW',
 'NEM',
 'IEMG',
 'VEU',
 'IONS',
 'GDX',
 'EEM',
 'VXUS',
 'PHYS',
 'LSCC',
 'HAL',
 'IXUS',
 'ETR',
 'EWJ',
 'MTZ',
 'OPEN',
 'SMH',
 'FNDX',
 'USO',
 'SOXL',
 'KLAC',
 'GDXJ',
 'MOD',
 'NBIS',
 'FTAI',
 'SIL',
 'MEDP',
 'VLO',
 'MPWR',
 'SPIB',
 'VRT',
 'SHEL',
 'AEM',
 'MBB',
 'TTMI',
 'JBHT',
 'BKR',
 'CNQ',
 'IDEV',
 'DD',
 'GFI',
 'ATI',
 'WELL',
 'FE',
 'JNK',
 'EQIX',
 'NVS',
 'FNV',
 'MTSI',
 'VTR',
 'NVT',
 'EIX',
 'SPHY',
 'AG',
 'FN',
 'PAAS',
 'GM',
 'AEP',
 'IBB',
 'RGLD',
 'AGI',
 'USHY',
 'TJX',
 'HII',
 'IEFA',
 'VYM',
 'XLE',
 'IUSB',
 'CLS',
 'CASY',
 'EFA',
 'XOM',
 'PEN',
 'ADI',
 'RPRX',
 'IWD',
 'SCHD',
 'MRK',
 'VTV',
 'PR',
 'HYG',
 'AGG',
 'APLD',
 'STLD',
 'MRVL',
 'IGIB',
 'VWO',
 'XPO',
 'SPG',
 'VCIT',
 'BND',
 'DGRO',
 'ARGX',
 'C',
 'CFG',
 'TSM',
 'VT',
 'CDE',
 'SLB',
 'IWN',
 'WMT',
 'FIVE',
 'BWXT']

In [12]:
SU.export_audit_to_excel(
    audit_pack=analyzer1.last_run, filename="Audit_Verification_Report.xlsx"
)

📂 [EXCEL AUDIT] Building full transparency report: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\Audit_Verification_Report.xlsx
✨ Audit Report Complete: C:\Users\ping\Files_win10\python\py311\stocks\notebooks_RLVR\output\Audit_Verification_Report.xlsx

WindowsPath('C:/Users/ping/Files_win10/python/py311/stocks/notebooks_RLVR/output/Audit_Verification_Report.xlsx')

In [13]:
##################################
##################################
##################################

In [14]:
import pathlib

# Set display width to prevent line wrapping
pd.set_option("display.width", 2000)

# Show all columns instead of truncated view
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)


def load_latest_finviz_parquet(data_dir: str) -> pd.DataFrame:
    path = pathlib.Path(data_dir)
    pattern = "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_df_finviz_merged_stocks_etfs.parquet"

    files = list(path.glob(pattern))

    if not files:
        print(f"DEBUG: No files matching pattern found in {path.absolute()}")
        return None

    latest_path = max(files, key=lambda x: x.name)
    print(f"DEBUG: Loading file: {latest_path.name}")

    try:
        return pd.read_parquet(latest_path)
    except Exception as e:
        print(f"DEBUG: Failed to read {latest_path.name}. Error: {e}")
        return None


# Usage
df_finviz = load_latest_finviz_parquet(DATA_DIR)
print(f"df_finviz:\n{df_finviz}")

DEBUG: Loading file: 2026-07-22_df_finviz_merged_stocks_etfs.parquet
df_finviz:
         No.                                            Company               Index                  Sector                                  Industry         Country Exchange                                               Info  MktCap AUM, M  Rank  Market Cap, M     P/E  Fwd P/E    PEG      P/S     P/B       P/C    P/FCF    Book/sh    Cash/sh  Dividend %  Dividend TTM Dividend Ex Date  Payout Ratio %       EPS  EPS next Q  EPS this Y %  EPS next Y %  EPS past 5Y %  EPS next 5Y %  Sales past 5Y %  Sales Q/Q %  EPS Q/Q %  EPS YoY TTM %  Sales YoY TTM %   Sales, M  Income, M  EPS Surprise %  Revenue Surprise %  Outstanding, M  Float, M  Float %  Insider Own %  Insider Trans %  Inst Own %  Inst Trans %  Short Float %  Short Ratio  Short Interest, M   ROA %     ROE %  ROIC %  Curr R  Quick R  LTDebt/Eq  Debt/Eq  Gross M %  Oper M %  Profit M %  Perf 3D %  Perf Week %  Perf Month %  Perf Quart %  Perf Half %  Perf Year %  Perf YTD %  Beta      ATR  ATR/Price %  Volatility W %  Volatility M %  SMA20 %  SMA50 %  SMA200 %  50D High %  50D Low %  52W High %  52W Low %              52W Range  All-Time High %  All-Time Low %    RSI  Earnings    IPO Date Optionable Shortable  Employees  Change from Open %  Gap %  Recom  Avg Volume, M  Rel Volume     Volume  Target Price  Prev Close       Open       High        Low      Price  Change %                                   Single Category                       Asset Type  Expense %  Holdings    AUM, M  Flows 1M, M  Flows% 1M  Flows 3M, M  Flows% 3M  Flows YTD, M  Flows% YTD  Return% 1Y  Return% 3Y  Return% 5Y                                               Tags    Sharpe 3d  Sortino 3d  Omega 3d  Sharpe 5d  Sortino 5d  Omega 5d  Sharpe 10d  Sortino 10d  Omega 10d  Sharpe 15d  Sortino 15d  Omega 15d  Sharpe 30d  Sortino 30d  Omega 30d  Sharpe 60d  Sortino 60d  Omega 60d  Sharpe 120d  Sortino 120d  Omega 120d  Sharpe 250d  Sortino 250d  Omega 250d
NVDA       1                                        NVIDIA Corp  DJIA, NDX, S&P 500              Technology                            Semiconductors             USA     NASD                         Technology, Semiconductors      5131850.0     1      5131850.0   32.48      NaN   0.35    20.24   26.28     63.69    43.10       8.07       3.33        0.31          0.28         6/4/2026            0.82      6.53        2.08           NaN           NaN            NaN            NaN              NaN        85.23     213.42         109.57            70.68  253490.00  159610.00            6.52                3.43        24220.00  23270.00    96.07           3.85            -0.33       70.45          0.00           1.33         1.99             310.13   82.97    114.29   77.17    3.44     2.85       0.06     0.07      74.15     64.02       62.97     4.5609        -0.21          1.63          6.09        19.09        26.96       13.71  2.22     7.36       3.4707            3.30            3.39     4.83     1.14     10.05      -10.35      11.73      -10.35      29.25        164.07 - 236.54           -10.35       636079.96  56.18  May 20/a   1/22/1999        Yes       Yes    42000.0                3.04  -0.72   1.23       156.2100        0.88  137645596        314.29      207.29     205.80     214.39     204.95     212.06      2.30                                                                                           NaN       NaN       NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -     144.9625   5155.4574  460.2846     4.2783      7.9370    2.0000      2.9345       5.1009     1.5689      3.3679       6.0642     1.7068      0.4983       0.7575     1.0783     -0.1022      -0.1494     0.9840       0.6176        0.9293      1.1040       0.6326        0.9307      1.1079
AAPL       2                                          Apple Inc  DJIA, NDX, S&P 500              Technology                      Consumer Electronics             USA     NASD                   Technology, Consumer Electronics      4786460.0     2      4786460.0   39.42      NaN   2.61    10.60   44.89     69.87    37.05       7.26       4.66        0.33          1.05        5/11/2026           13.66      8.27        1.89           NaN           NaN            NaN            NaN              NaN        16.60      22.04          28.91            12.76  451440.00  122580.00            3.30                1.58        14690.00  14670.00    99.88           0.12            -2.21       67.21          0.00           0.96         2.56             140.53   34.91    141.47   67.76    1.07     1.02       0.70     0.80      47.86     32.64       27.15    -2.3521        -0.49          9.72         22.44        32.10        52.00       19.87  1.08     8.02       2.4610            2.27            2.78     5.10     6.89     18.38       -2.72      19.05       -2.72      61.73        201.50 - 334.99            -2.72       512176.75  62.54  Jul 30/a  12/12/1980        Yes       Yes   166000.0               -0.60   0.04   2.04        54.9500        0.71   38755929        321.28      327.74     327.87     329.00     323.34     325.89     -0.56                                                                                           NaN       NaN       NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -      -2.9893     -4.7212    0.5794    -7.9864     -8.0767    0.1696      3.0336       6.6324     1.7823      6.2386      17.4759     3.2762      3.1149       4.8930     1.7400      3.0091       4.6968     1.6837       1.8150        2.7393      1.3636       1.7100        2.7226      1.3544
GOOG       3                                       Alphabet Inc        NDX, S&P 500  Communication Services            Internet Content & Information             USA     NASD  Communication Services, Internet Content & Inf...      4168870.0     3      4168870.0   26.08      NaN   1.36     9.85    8.65     32.87    64.70      39.51      10.40        0.25          0.85         6/8/2026            7.68     13.11        3.01           NaN           NaN            NaN            NaN              NaN        22.34      81.96          46.22            17.77  423170.00  160210.00          216.66                2.34         5460.00   5090.00    93.37          58.15            -0.03       27.58          0.00           1.15         2.69              58.49   27.17     38.88   28.04    1.92     1.92       0.19     0.20      60.43     33.63       37.86    -1.2163        -7.64         -1.97          3.46         6.13        77.98        8.96  1.24    10.92       3.1938            2.98            2.77    -3.10    -6.33      6.03      -15.47       2.46      -15.47      81.39        188.49 - 404.47           -15.47         1306.39  41.69  Jul 22/b   3/27/2014        Yes       Yes   190820.0               -1.52   0.29   1.38        21.7400        1.07   23273840        437.79      346.19     347.18     349.45     341.64     341.91     -1.24                                                                                           NaN       NaN       NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -    -129.3834    -15.8151    0.0000    -8.3944     -9.2954    0.3043     -2.9163      -3.8669     0.6352     -2.4619      -3.3375     0.6763     -1.3718      -1.8632     0.8023     -0.1397      -0.2324     0.9747       0.1088        0.1772      1.0192       1.9343        3.4768      1.4070
GOOGL      4                                       Alphabet Inc  DJIA, NDX, S&P 500  Communication Services            Internet Content & Information             USA     NASD  Communication Services, Internet Content & Inf...      4159530.0     4      4159530.0   26.10      NaN   1.35     9.83    8.66     32.79    64.56      39.51      10.43        0.25          0.85         6/8/2026            7.68     13.11        3.01           NaN           NaN            NaN            NaN              NaN        22.34      81.96          46.22            17.77  423170.00  160210.00          216.61                2.33        12170.00   5830.00    47.91          52.09            -0.04       39.25          0.00           1.47         2.70              85.86   27.17     38.88   28.04    1.92     1.92       0.19     0.20      60.43     33.63       37.86    -1.3496        -7.77         -2.17          2.95         6.24        78.79        9.29  1.24    11.07       3.2360            2.98            2.88    -3.57    -6.91      5.85      -16.28       3.60      -16.28      82.49        187.46 - 408.61           -16.28        14145.89  40.55  Jul 22/b   8/19/2004        Yes       Yes   190820.0               -1.74   0.29   1.38        31.8400        1.24   39334140        437.93      347.15     348.15     349.94     341.73     342.09     -1.46                                                                                           NaN       NaN       NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -    -389.5184    -15.8679    0.0000    -8.6900     -9.4822    0.2950     -3.5232      -4.4895     0.5846     -3.0938      -3.9510     0.6134     -1.5601      -2.0787     0.7769     -0.2002      -0.3270     0.9638       0.1213        0.1958      1.0214       1.9359        3.4606      1.4083
MSFT       5                                     Microsoft Corp  DJIA, NDX, S&P 500              Technology                 Software - Infrastructure             USA     NASD              Technology, Software - Infrastructure      2899620.0     5      2899620.0   23.25      NaN   1.08     9.11    7.00     37.05    39.77      55.78      10.54        0.94          3.56        8/20/2026           24.34     16.79        4.24           NaN           NaN            NaN            NaN              NaN        18.30      23.32          29.64            17.87  318270.00  125220.00            5.18                1.77         7430.00   7310.00    98.46           1.54            -0.03       75.98         -1.37           1.22         2.27              89.06   19.93     34.01   24.02    1.28     1.27       0.26     0.30      68.31     46.80       39.34    -0.8837        -1.34          6.26         -7.97       -14.12       -22.75      -19.29  1.12    11.92       3.0537            2.85            2.98     1.48    -2.49    -10.79      -16.29      11.78      -29.73      11.78        349.20 - 555.45           -29.73       489792.90  49.17  Jul 29/a   3/13/1986        Yes       Yes   228000.0               -2.31   0.46   1.23        39.2400        0.72   28142511        555.30      397.75     399.58     401.00     386.96     390.34     -1.86                                                                                           NaN       NaN       NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -     -46.2067    -15.4259    0.0000    -5.6614     -7.5411    0.4398      1.4809       2.4909     1.2392      1.0761       1.7307     1.1707     -0.7680      -1.1286     0.8883     -0.9928      -1.4275     0.8539      -0.6450       -0.9149      0.9004      -0.9603       -1.2648      0.8446
AMZN       6                                     Amazon.com Inc  DJIA, NDX, S&P 500       Consumer Cyclical                           Internet Retail             USA     NASD                 Consumer Cyclical, Internet Retail      2633880.0     6      2633880.0   29.26      NaN   1.10     3.55    5.96     18.04      NaN      41.09      13.57         NaN           NaN                -            0.00      8.37        1.81           NaN           NaN            NaN            NaN              NaN        16.61      75.33          35.55            14.22  742780.00   90800.00           70.22                2.39        10750.00   9790.00    91.07           8.95            -0.03       67.73          0.00           1.02         2.05             100.35   11.64     24.28   13.93    1.18     1.01       0.47     0.51      50.60     12.14       12.22    -0.9627        -3.97          5.18         -2.02         6.00         7.64        6.08  1.46     7.09       2.8957            2.49            2.87     0.51    -2.30      4.43      -10.88       8.56      -12.10      24.92        196.00 - 278.56           -12.10       373004.79  48.40  Jul 30/a   5/15/1997        Yes       Yes  1576000.0               -1.38   0.29   1.21        48.9400        0.70   34112732        316.99      247.55     248.26     248.45     242.45     244.85     -1.09                                                                                           NaN       NaN       NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -    -205.4546    -15.8509    0.0000    -7.6289     -8.9787    0.3462     -1.0866      -1.7715     0.8403      1.0205       1.6916     1.1727      0.1041       0.1441     1.0169     -0.9709      -1.2772     0.8596       0.1131        0.1597      1.0181       0.1990        0.2842      1.0343
TSM        7             Taiwan Semiconductor Manufacturing ADR                   -              Technology                            Semiconductors          Taiwan     NYSE                         Technology, Semiconductors      2184600.0     7      2184600.0   30.40      NaN   0.53    15.30   11.86     19.78    54.75      35.53      21.29        0.97          3.50        9/16/2026           25.98     13.86        4.34           NaN           NaN            NaN            NaN              NaN        32.92      73.33          54.80            34.60  142820.00   71860.00           10.78               -1.20         5190.00   5180.00    99.91           0.09            -3.69       15.18          9.73           0.54         1.94              27.73   26.90     40.06   31.58    2.46     2.25       0.13     0.15      63.38     55.84       50.31     5.7334         0.41         -9.93         14.43        28.75        79.54       38.61  1.39    18.36       4.3589            3.16            3.83    -2.38    -1.06     19.08      -12.06       9.39      -12.06      88.29        223.70 - 479.00           -12.06        16119.68  48.26  Jul 16/b   10/8/1997        Yes       Yes        NaN                1.52  -2.29   1.21        14.2800        0.72   10259585        523.90      424.61     414.90     424.81     414.21     421.21     -0.80                                                                                           NaN       NaN       NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -       8.3363     64.7860    6.7716     3.2309      7.8967    1.8020     -2.4285      -3.9178     0.6471     -2.1446      -3.1588     0.6949     -0.0038      -0.0055     0.9994      0.5222       0.7650     1.0886       1.1560        1.7512      1.2068       1.5386        2.3729      1.2881
AVGO       8                                       Broadcom Inc        NDX, S&P 500              Technology                            Semiconductors             USA     NASD                         Technology, Semiconductors      1887860.0     8      1887860.0   66.06      NaN   0.36    25.02   21.53     96.18    57.62      18.43       4.13        0.66          2.54        6/22/2026           49.52      6.01        3.21           NaN           NaN            NaN            NaN              NaN        47.87      85.59         125.17            32.29   75470.00   29320.00            1.82                0.26         4760.00   4670.00    98.08           1.91            -1.96       79.97         -0.09           1.50         2.68              70.12   17.06     37.28   19.50    2.24     2.01       0.71     0.74      65.66     44.14       38.85     7.0059         0.64          1.19         -1.33        19.31        42.44       14.65  1.47    16.84       4.2438            3.87            3.53     4.22    -1.00      8.89      -19.84      11.33      -19.84      45.35        273.00 - 495.00           -19.84        27590.86  53.57  Jun 03/a    8/6/2009        Yes       Yes    33000.0                4.37  -1.63   1.32        26.1800        0.65   16966188        528.60      386.50     380.20     398.58     380.00     396.81      2.67                                                                                           NaN       NaN       NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -     117.5952   5155.4574  460.2846    13.9953     47.0064    6.9223     -0.5776      -0.7370     0.9121      2.9187       4.5596     1.5537      0.3951       0.5589     1.0594     -0.1941      -0.2505     0.9691       0.9692        1.3961      1.1735       0.8471        1.2562      1.1586
META       9                                 Meta Platforms Inc        NDX, S&P 500  Communication Services            Internet Content & Information             USA     NASD  Communication Services, Internet Content & Inf...      1592020.0     9      1592020.0   22.80      NaN   0.89     7.41    6.53     19.53    32.99      96.01      32.11        0.31          2.10        6/15/2026            8.94     27.51        7.19           NaN           NaN            NaN            NaN              NaN        33.08      62.49           6.07            26.18  214960.00   70590.00           55.89                1.36         2200.00   2190.00    99.76          13.70            -0.06       68.44          0.52           1.57         1.90              34.49   20.90     32.93   21.52    2.35     2.35       0.35     0.36      81.94     41.21       32.84    -2.9164        -7.95         11.23         -6.23         3.82       -11.02       -4.99  1.24    24.78       3.9511            3.23            3.61     1.82     3.48     -1.88       -8.59      16.10      -21.23      20.55        520.26 - 796.25           -21.23         3473.62  51.52  Jul 29/a   5/18/2012        Yes       Yes    78865.0               -3.17   0.60   1.29        18.1300        0.61   11019559        822.72      643.81     647.70     649.00     624.00     627.17     -2.58                                                                                           NaN       NaN       NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -     -14.5076    -12.5552    0.0000   -15.7042    -11.9443    0.0000     -0.2902      -0.5197     0.9521      0.9683       1.6057     1.1608      1.3742       2.3734     1.2555     -0.5954      -0.8403     0.8974      -0.7064       -0.9826      0.8824      -0.2405       -0.3515      0.9561

In [15]:
import ast

try:
    result = df_finviz.loc[target_tickers]
except KeyError as e:
    # Extract missing tickers from pandas error message
    error_msg = str(e)
    missing_str = error_msg.replace(" not in index", "").strip('"').strip("'")
    missing_tickers = ast.literal_eval(missing_str)

    print(f"Missing tickers: {missing_tickers}")

    # Remove missing tickers and retry
    target_tickers_in_finviz = [t for t in target_tickers if t not in missing_tickers]
    result = df_finviz.loc[target_tickers_in_finviz]

# print(f'missing_tickers: {missing_tickers}\n')
print(f"result:\n{result}")

Missing tickers: ['GTLS', 'OPEN', 'USO', 'SIL']
result:
        No.                                            Company               Index                  Sector                                  Industry         Country Exchange                                               Info  MktCap AUM, M  Rank  Market Cap, M     P/E  Fwd P/E   PEG      P/S     P/B      P/C   P/FCF  Book/sh  Cash/sh  Dividend %  Dividend TTM Dividend Ex Date  Payout Ratio %    EPS  EPS next Q  EPS this Y %  EPS next Y %  EPS past 5Y %  EPS next 5Y %  Sales past 5Y %  Sales Q/Q %  EPS Q/Q %  EPS YoY TTM %  Sales YoY TTM %   Sales, M  Income, M  EPS Surprise %  Revenue Surprise %  Outstanding, M  Float, M  Float %  Insider Own %  Insider Trans %  Inst Own %  Inst Trans %  Short Float %  Short Ratio  Short Interest, M  ROA %    ROE %  ROIC %  Curr R  Quick R  LTDebt/Eq  Debt/Eq  Gross M %  Oper M %  Profit M %  Perf 3D %  Perf Week %  Perf Month %  Perf Quart %  Perf Half %  Perf Year %  Perf YTD %  Beta     ATR  ATR/Price %  Volatility W %  Volatility M %  SMA20 %  SMA50 %  SMA200 %  50D High %  50D Low %  52W High %  52W Low %         52W Range  All-Time High %  All-Time Low %    RSI  Earnings    IPO Date Optionable Shortable  Employees  Change from Open %  Gap %  Recom  Avg Volume, M  Rel Volume    Volume  Target Price  Prev Close     Open     High      Low    Price  Change %                                 Single Category            Asset Type  Expense %  Holdings    AUM, M  Flows 1M, M  Flows% 1M  Flows 3M, M  Flows% 3M  Flows YTD, M  Flows% YTD  Return% 1Y  Return% 3Y  Return% 5Y                                               Tags   Sharpe 3d  Sortino 3d  Omega 3d  Sharpe 5d  Sortino 5d  Omega 5d  Sharpe 10d  Sortino 10d  Omega 10d  Sharpe 15d  Sortino 15d  Omega 15d  Sharpe 30d  Sortino 30d  Omega 30d  Sharpe 60d  Sortino 60d  Omega 60d  Sharpe 120d  Sortino 120d  Omega 120d  Sharpe 250d  Sortino 250d  Omega 250d
SGOV     26                iShares 0-3 Month Treasury Bond ETF                   -               Financial                      Exchange Traded Fund             USA     NYSE  Financial, Exchange Traded Fund, Bonds - Treas...        99130.0   184            NaN     NaN      NaN   NaN      NaN     NaN      NaN     NaN      NaN      NaN        3.80          3.82         7/1/2026             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN        NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.39               7.81    NaN      NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     0.0199         0.06          0.00          0.01         0.04        -0.02        0.22  0.00    0.03       0.0298            0.01            0.01     0.05     0.06      0.08       -0.08       0.21       -0.14       0.33   100.27 - 100.74            -0.15            0.64  59.90         -   5/28/2020        Yes       Yes        NaN                0.00   0.00    NaN        20.2000        0.63  12644486           NaN      100.60   100.60   100.61   100.60   100.60      0.00                   Bonds - Treasury & Government                 Bonds       0.09      24.0   99130.0          NaN       3.93     14840.00      17.61      30290.00       44.00        3.88        4.68        3.63              U.S., fixed-income, treasuries, bonds    -24.6201    -14.4441    0.0000    -4.3675     -6.0890    0.5034     -4.1649      -5.0351     0.5258     -2.2816      -3.2244     0.6997     -1.9565      -2.8460     0.7369     -2.1573      -3.2599     0.7169      -2.1221       -3.0248      0.7265      -1.0289       -1.5604      0.8539
SHV     130                 iShares 0-1 Year Treasury Bond ETF                   -               Financial                      Exchange Traded Fund             USA     NYSE  Financial, Exchange Traded Fund, Bonds - Treas...        20740.0   732            NaN     NaN      NaN   NaN      NaN     NaN      NaN     NaN      NaN      NaN        3.78          4.17         7/1/2026             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN        NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.85               2.13    NaN      NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     0.0181         0.05          0.02         -0.02        -0.05        -0.05        0.11  0.01    0.03       0.0272            0.01            0.01     0.06     0.05      0.02       -0.10       0.22       -0.21       0.23   110.02 - 110.50            -1.89            2.02  58.10         -   1/11/2007        Yes       Yes        NaN                0.01   0.01    NaN         2.4900        1.13   2807918           NaN      110.25   110.26   110.27   110.26   110.27      0.02                   Bonds - Treasury & Government                 Bonds       0.15      65.0   20740.0          NaN      -0.00        80.49       0.39        827.55        4.16        3.81        4.60        3.41              U.S., fixed-income, treasuries, bonds     -9.3541    -10.2045    0.0909    -1.9030     -2.7804    0.7147     -2.6705      -3.3513     0.6572     -0.8966      -1.2209     0.8627     -1.7018      -2.2286     0.7436     -2.5427      -3.2770     0.6503      -2.6345       -3.4998      0.6534      -1.0914       -1.6403      0.8329
BIL      54   State Street SPDR Bloomberg 1-3 Month T-Bill ETF                   -               Financial                      Exchange Traded Fund             USA     NYSE  Financial, Exchange Traded Fund, Bonds - Treas...        47110.0   392            NaN     NaN      NaN   NaN      NaN     NaN      NaN     NaN      NaN      NaN        3.81          3.49         7/1/2026             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN        NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         1.08              10.72    NaN      NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     0.0328         0.07          0.01          0.01         0.04        -0.10        0.22  0.00    0.03       0.0328            0.01            0.01     0.06     0.06      0.06       -0.09       0.21       -0.22       0.35     91.26 - 91.78           -13.74            0.41  60.29         -   5/30/2007        Yes       Yes        NaN                0.00   0.02    NaN         9.9400        0.67   6656868           NaN       91.56    91.58    91.58    91.57    91.58      0.02                   Bonds - Treasury & Government                 Bonds       0.14      19.0   47110.0          NaN       1.33       296.71       0.63       4330.00       10.12        3.79        4.59        3.51              U.S., fixed-income, treasuries, bonds     -5.0887     -7.0027    0.3761    -3.3676     -4.2365    0.5738     -1.5441      -2.5284     0.7725     -1.8358      -2.7020     0.7433     -1.3866      -2.1158     0.8055     -1.9627      -2.6861     0.7387      -2.2329       -2.9892      0.7114      -1.2650       -1.8308      0.8246
MINT    158           PIMCO Enhanced Short Maturity Active ETF                   -               Financial                      Exchange Traded Fund             USA     NYSE  Financial, Exchange Traded Fund, Bonds - Broad...        16910.0   831            NaN     NaN      NaN   NaN      NaN     NaN      NaN     NaN      NaN      NaN        4.22          4.25         7/1/2026             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN        NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.20               0.31    NaN      NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     0.0199         0.07         -0.03          0.10         0.06         0.18        0.32  0.02    0.05       0.0497            0.02            0.03     0.04     0.06      0.13       -0.16       0.24       -0.16       0.39   100.27 - 100.82            -1.07            4.44  55.98         -  11/17/2009        Yes       Yes        NaN                0.02  -0.04    NaN         1.5400        0.60    923499           NaN      100.68   100.64   100.67   100.64   100.66     -0.02                            Bonds - Broad Market                 Bonds       0.36    1028.0   16910.0          NaN       3.35      1400.00       9.03       2290.00       15.69        4.57        5.34        3.58         U.S., fixed-income, bonds, debt-securities     -4.9275     -6.8487    0.3899    -2.3322     -3.0227    0.6690     -1.8232      -2.1362     0.7305     -2.7674      -3.3962     0.6477     -0.4793      -0.6714     0.9246      0.4765       0.6833     1.0787       0.4732        0.7026      1.0832       1.4698        2.3510      1.2752
USFR    143             WisdomTree Floating Rate Treasury Fund                   -               Financial                      Exchange Traded Fund             USA     NYSE  Financial, Exchange Traded Fund, Bonds - Treas...        18150.0   789            NaN     NaN      NaN   NaN      NaN     NaN      NaN     NaN      NaN      NaN        3.83          1.93        6/25/2026             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN        NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.33               1.49    NaN      NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     0.0198         0.06          0.04          0.06         0.08         0.02        0.30 -0.00    0.02       0.0396            0.02            0.02     0.12     0.13      0.19       -0.02       0.32       -0.04       0.48     50.23 - 50.49            -9.53            3.83  66.17         -    2/4/2014        Yes       Yes        NaN               -0.02   0.04    NaN         4.5600        0.66   3014986           NaN       50.46    50.48    50.48    50.47    50.47      0.02                   Bonds - Treasury & Government                 Bonds       0.15       4.0   18150.0          NaN       3.91       977.76       5.69       1720.00       10.49        3.95        4.73        3.77  U.S., fixed-income, treasuries, floating-rate,...     -8.9904     -9.9842    0.1105    -0.6396     -0.8940    0.8874     -0.3697      -0.5069     0.9401     -0.2559      -0.3549     0.9597     -0.0637      -0.0907     0.9903     -0.2315      -0.3393     0.9648      -1.0112       -1.3459      0.8554      -0.4219       -0.5761      0.9363
BOXX    199                  Alpha Architect 1-3 Month Box ETF                   -               Financial                      Exchange Traded Fund             USA     CBOE  Financial, Exchange Traded Fund, Bonds - Treas...        13050.0   997            NaN     NaN      NaN   NaN      NaN     NaN      NaN     NaN      NaN      NaN         NaN           NaN        8/13/2024             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN        NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.02               0.06    NaN      NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     0.0255         0.06          0.38          0.92         1.87         4.06        2.10 -0.00    0.04       0.0340            0.02            0.03     0.18     0.40      1.55        0.00       0.77        0.00       4.06   112.93 - 117.52             0.00           17.81  90.95         -  12/28/2022        Yes       Yes        NaN               -0.02   0.03    NaN         2.3000        0.52   1188096           NaN      117.50   117.54   117.54   117.52   117.52      0.02                   Bonds - Treasury & Government                 Bonds       0.19       9.0   13050.0          NaN       2.92      1920.00      17.21       3500.00       36.60        4.08        4.72         NaN                   U.S., treasuries, options, bonds     -9.7105    -10.4130    0.0723   -10.1944     -9.4963    0.0990      1.1995       2.3403     1.2672      6.2463      18.2661     3.6008     -0.1919      -0.2776     0.9693     -0.7144      -1.0525     0.8892      -0.5280       -0.7739      0.9123       0.0724        0.1081      1.0122
PULS    150                          PGIM Ultra Short Bond ETF                   -               Financial                      Exchange Traded Fund             USA     NYSE  Financial, Exchange Traded Fund, Bonds - Broad...        17720.0   803            NaN     NaN      NaN   NaN      NaN     NaN      NaN     NaN      NaN      NaN        4.51          2.24        6/30/2026             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN        NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.15               0.35    NaN      NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN     0.0201         0.06          0.00         -0.02        -0.12        -0.16        0.12  0.01    0.03       0.0604            0.04            0.04     0.06     0.05     -0.04       -0.16       0.24       -0.38       0.30     49.50 - 49.84            -2.65            6.09  57.22         -   4/10/2018        Yes       Yes        NaN                0.00   0.00    NaN         2.4400        1.06   2584782           NaN       49.65    49.65    49.66    49.64    49.65      0.00                            Bonds - Broad Market                 Bonds       0.15     917.0   17720.0          NaN       2.24      2210.00      14.24       4390.00       32.88        4.51        5.49        4.22        U.S., fixed-income, bonds, investment-grade      2.3822      6.0479    1.5388    -0.3982     -0.6115    0.9416     -0.1571      -0.2175     0.9743     -1.1633      -1.5073     0.8281     -0.1247      -0.1642     0.9779     -0.2935      -0.4032     0.9530      -0.2822       -0.3895      0.9564       0.9843        1.5038      1.1716
JPST     72                    JPMorgan Ultra-Short Income ETF                   -               Financial                      Exchange Traded Fund             USA     NYSE  Financial, Exchange Traded Fund, Bonds - Broad...        39990.0   450            NaN     NaN      NaN   NaN      NaN     NaN      NaN     NaN      NaN      NaN        4.23          2.13         7/1/2026             NaN    NaN         NaN           NaN           NaN            NaN            NaN              NaN          NaN        NaN            NaN              NaN        NaN        NaN             NaN                 NaN             NaN       NaN      NaN            NaN              NaN         NaN           NaN            NaN         0.17               1.10    NaN      NaN     NaN     NaN      NaN        NaN      NaN        NaN       NaN         NaN    -0.0198         0.02          0.02         -0.14        -0.37        -0.26       -0.20  0.01    0.03       0.0594            0.04            0.04     0.01    -0.00     -0.21       -0.26       0.20       -0.59       0.20     50.39 - 50.79            -0.59           10.52  51.54         -   5/19/2017        Yes       Yes        NaN               -0.02   0.04    NaN         6.3500        0.62   3926213           NaN       50.48    50.50    50.50    50.48    50.49      0.02                            Bonds - Broad Market                 Bonds       0.18     790.0   39990.0          NaN       2.53      2440.00       6.51       4680.00       13.25        4.06        5.13        3.70  U.S., fixed-income, debt-securities, volatilit...     -8.9940     -9.9864    0.1103    -5.8332     -6.8700    0.3880     -3.9731      -5.1154     0.5420     -1.6145      -2.1563     0.7749     -0.3403      -0.4496     0.9458     -0.8847      -1.1918     0.8706      -1.4247       -1.8738      0.7955       0.0532        0.0778      1.0090
SNDK     62                                       Sandisk Corp        NDX, S&P 500              Technology                         Computer Hardware             USA     NASD                      Technology, Computer Hardware       236840.0    67       236840.0   55.59      NaN   NaN    17.96   17.18    63.41   53.10    93.09    25.22         NaN           NaN                -             NaN  28.77       34.67           NaN           NaN            NaN            NaN              NaN       251.03     272.72         395.16            82.76   13180.00    4510.00           60.09               26.06          148.00    146.13    98.74           1.33            -0.49       79.73         -4.61           4.93         0.54               7.20  30.01    39.30   32.29    4.78     3.62       0.01     0.02      56.04     41.58       34.19    18.0430        -0.97        -29.66         77.01       252.95      3766.71      573.72  5.04  193.68      12.1105            9.04            9.83   -10.40    -7.54     99.20      -32.07      25.20      -32.07    3888.20   40.10 - 2354.39           -32.07         5635.23  46.63  Aug 05/a   2/13/2025        Yes       Yes    11000.0                4.80  -3.99   1.67        13.2400        0.80  10539116       2363.65     1589.40  1526.00  1628.40  1516.01  1599.27      0.62                                                                              NaN       NaN       NaN          NaN        NaN          NaN        NaN           NaN         NaN         NaN         NaN         NaN                                                  -     12.2205   5155.4574  460.2846     6.9013     26.7778    4.3737     -2.3514      -3.1256     0.6836     -2.4842      -3.1485     0.6775      0.5180       0.7888     1.0844      1.9512       3.1285     1.3665       2.5689        4.1511      1.5027       3.8693        6.8969      1.9202

In [16]:
def cleanup_ui():
    clear_output(wait=True)
    pio.renderers.default = None
    gc.collect()
    print("🧹 Memory Cleared.")


def active_engine_audit():
    gc.collect()
    engines = [obj for obj in gc.get_objects() if type(obj).__name__ == "AlphaEngine"]
    print(f"Active AlphaEngine Instances: {len(engines)}")


active_engine_audit()

Active AlphaEngine Instances: 1

In [17]:
# print(features_df.info())
# display(features_df.head())
# display(df_indices.tail())

In [18]:
################################
################################
################################
################################

In [19]:
SU.peek(0, result)

❌ Error: Pass the result map (list), not the analyzer object.

In [20]:
features_df.loc["TSLA"]

                ATR    ATRP     TRP      RSI  Mom_21  Consistency       IR_63  Beta_63   DD_21  AutoCorr_15      Ret_1d  Range_Pos_20   Slope_P_5  Slope_V_5   Convexity  RollingStalePct  RollMedDollarVol  RollingSameVolCount
Date
2010-06-29      NaN  0.0000  0.0000  50.0000     NaN          NaN         NaN   1.0000  0.0000   0.0000e+00         NaN           NaN         NaN        NaN  0.0000e+00              NaN               NaN                  NaN
2010-06-30   0.4747  0.2988  0.2988   0.0000     NaN          NaN         NaN   1.0000  0.0000   0.0000e+00 -2.5115e-03           NaN         NaN        NaN  0.0000e+00              NaN               NaN                  NaN
2010-07-01   0.4677  0.3194  0.2573   0.0000     NaN          NaN         NaN   1.0000  0.0000   0.0000e+00 -7.8474e-02           NaN         NaN        NaN  0.0000e+00              NaN               NaN                  NaN
2010-07-02   0.4552  0.3556  0.2286   0.0000     NaN          NaN         NaN   1.0000  0.0000   0.0000e+00 -1.2568e-01           NaN         NaN        NaN  0.0000e+00              NaN               NaN                  NaN
2010-07-06   0.4425  0.4120  0.2588   0.0000     NaN          0.0         NaN   1.0000  0.0000   0.0000e+00 -1.6094e-01           NaN -1.0041e-01    -0.6060  0.0000e+00              NaN               NaN                  NaN
2010-07-07   0.4188  0.3976  0.1044   0.0000     NaN          0.0         NaN   1.0000  0.0000   0.0000e+00 -1.9246e-02           NaN -1.1317e-01    -0.5517  0.0000e+00              NaN               NaN                  NaN
2010-07-08   0.3981  0.3420  0.1117  18.8807     NaN          0.2         NaN   1.0000  0.0000   0.0000e+00  1.0507e-01           NaN -6.5352e-02    -0.3117  3.5056e-02              NaN               NaN                  NaN
2010-07-09   0.3761  0.3242  0.0776  18.7429     NaN          0.2         NaN   1.0000  0.0000   0.0000e+00 -3.4364e-03           NaN -1.1641e-02    -0.1776  1.0153e-01              NaN               NaN                  NaN
2010-07-12   0.3544  0.3118  0.0628  17.9217     NaN          0.2         NaN   1.0000  0.0000   0.0000e+00 -2.0112e-02           NaN  2.0989e-02    -0.0842  8.6341e-02              NaN               NaN                  NaN
2010-07-13   0.3373  0.2789  0.0959  28.4384     NaN          0.4         NaN   1.0000  0.0000   0.0000e+00  6.3924e-02           NaN  2.5246e-02     0.0127  3.6887e-02              NaN               NaN                  NaN
2010-07-14   0.3246  0.2454  0.1205  41.1132     NaN          0.6         NaN   1.0000  0.0000   0.0000e+00  9.3721e-02           NaN  2.9723e-02     0.0470  8.7337e-03              NaN               NaN                  NaN
2010-07-15   0.3133  0.2363  0.1257  41.4413     NaN          0.6         NaN   1.0000  0.0000   0.0000e+00  2.5176e-03           NaN  4.1904e-02     0.3167  1.6658e-02              NaN               NaN                  NaN
2010-07-16   0.2977  0.2163  0.0683  46.2821     NaN          0.8         NaN   1.0000  0.0000   0.0000e+00  3.7707e-02           NaN  4.7426e-02     0.4612  1.7703e-02              NaN               NaN                  NaN
2010-07-19   0.2841  0.1945  0.0735  53.3193     NaN          1.0         NaN   1.0000  0.0000   0.0000e+00  6.1533e-02           NaN  4.1719e-02     0.4517 -1.8574e-04              NaN               NaN                  NaN
2010-07-20   0.2726  0.2015  0.0916  45.2298     NaN          0.8         NaN   1.0000  0.0000   0.0000e+00 -7.3487e-02           NaN  1.4256e-02     0.2703 -3.3170e-02              NaN               NaN                  NaN
2010-07-21   0.2598  0.1928  0.0692  44.8658     NaN          0.6         NaN   1.0000  0.0000   0.0000e+00 -3.9384e-03           NaN  1.6298e-03     0.0594 -4.0089e-02              NaN               NaN                  NaN
2010-07-22   0.2462  0.1758  0.0491  49.1642     NaN          0.6         NaN   1.0000  0.0000   4.0108e-01  3.8576e-02           NaN -4.5690e-03    -0.0409 -1.8825e-02              NaN               NaN                  NaN
2010-07-23   0.2313  0.1629  0.0263  50.7028     NaN          0.6         NaN   1.0000  0.0000   4.2296e-01  1.3807e-02           NaN -2.3517e-03    -0.0460 -3.9814e-03              NaN               NaN                  NaN
2010-07-26   0.2205  0.1578  0.0573  48.8368     NaN          0.4         NaN   1.0000  0.0000   3.4610e-01 -1.5965e-02           NaN  1.1461e-02     0.0092  1.6030e-02              NaN               NaN                  NaN
2010-07-27   0.2091  0.1526  0.0448  46.6602     NaN          0.4         NaN   1.0000  0.0000   5.0377e-02 -1.9095e-02        0.3608  2.9996e-03    -0.0086  5.3513e-03              NaN               NaN                  NaN
2010-07-28   0.1960  0.1419  0.0188  47.7261     NaN          0.6         NaN   1.0000 -0.1327  -1.2111e-01  8.2701e-03        0.3718 -6.2225e-03    -0.0471 -1.7683e-02              NaN               NaN                  NaN
2010-07-29   0.1862  0.1372  0.0432  45.5907 -0.1482          0.4         NaN   1.0000 -0.1460  -7.5197e-03 -1.7852e-02        0.4909 -1.0135e-02    -0.0707 -1.3134e-02              NaN               NaN                  NaN
2010-07-30   0.1771  0.1333  0.0446  43.2787 -0.1632          0.2         NaN   1.0000 -0.0920   8.1844e-02 -2.0152e-02        0.6108 -1.0861e-02    -0.0556 -4.6384e-03              NaN               NaN                  NaN
2010-08-02   0.1694  0.1215  0.0492  49.8272 -0.0474          0.4         NaN   1.0000 -0.0452   1.8456e-02  4.9153e-02        0.8171 -2.6776e-04    -0.0161  9.8670e-03              NaN               NaN                  NaN
2010-08-03   0.1627  0.1112  0.0515  55.6248  0.1432          0.6         NaN   1.0000  0.0000   1.3433e-01  4.9230e-02        0.9587  1.4296e-02     0.0547  2.5157e-02              NaN               NaN                  NaN
2010-08-04   0.1574  0.1110  0.0626  51.3441  0.3197          0.4         NaN   1.0000 -0.0314  -1.0391e-01 -3.1435e-02        0.8518  1.8352e-02     0.0757  1.8620e-02              NaN               NaN                  NaN
2010-08-05   0.1533  0.1124  0.0733  46.7918  0.2943          0.4         NaN   1.0000 -0.0683  -2.0988e-02 -3.8100e-02        0.6842  6.6627e-03     0.0140 -7.6333e-03              NaN               NaN                  NaN
2010-08-06   0.1468  0.1124  0.0475  42.4851  0.1220          0.4         NaN   1.0000 -0.1075   6.6211e-02 -4.2051e-02        0.5028 -2.0216e-02    -0.1103 -3.8568e-02              NaN               NaN                  NaN
2010-08-09   0.1388  0.1062  0.0270  42.5516  0.1264          0.4         NaN   1.0000 -0.1071  -7.0682e-02  5.1302e-04        0.5047 -3.0827e-02    -0.1226 -3.7490e-02              NaN               NaN                  NaN
2010-08-10   0.1328  0.1047  0.0436  39.7429  0.1161          0.2         NaN   1.0000 -0.1330   2.0830e-01 -2.9082e-02        0.2829 -2.6406e-02    -0.1056 -6.1898e-03              NaN               NaN                  NaN
2010-08-11   0.1290  0.1081  0.0659  34.8337 -0.0132          0.2         NaN   1.0000 -0.1845   3.1479e-01 -5.9385e-02        0.0114 -2.9536e-02    -0.1263  1.2906e-03              NaN               NaN                  NaN
2010-08-12   0.1222  0.1041  0.0290  33.6455 -0.1129          0.2         NaN   1.0000 -0.1982   3.2863e-01 -1.6760e-02        0.0432 -3.0498e-02    -0.1727 -4.0921e-03              NaN               NaN                  NaN
2010-08-13   0.1175  0.0962  0.0464  39.0214 -0.0789          0.4         NaN   1.0000 -0.1654   2.2404e-01  4.0909e-02        0.1914 -2.1321e-02    -0.1634  8.2159e-03              NaN               NaN                  NaN
2010-08-16   0.1117  0.0892  0.0288  42.2413 -0.0901          0.4         NaN   1.0000 -0.1444   3.2057e-01  2.5112e-02        0.2902 -3.2610e-04    -0.0194  3.0172e-02              NaN               NaN                  NaN
2010-08-17   0.1067  0.0835  0.0324  44.7678 -0.1260          0.6         NaN   1.0000 -0.1276   3.4967e-01  1.9704e-02        0.3674  1.9991e-02     0.0904  4.1312e-02              NaN               NaN                  NaN
2010-08-18   0.1038  0.0829  0.0527  42.7016 -0.0754          0.6         NaN   1.0000 -0.1449   3.3349e-01 -1.9849e-02        0.2881  1.7304e-02     0.0871  1.7630e-02              NaN               NaN                  NaN
2010-08-19   0.1007  0.0804  0.0490  42.8518 -0.0707          0.8         NaN   1.0000 -0.1440   3.3842e-01  1.0709e-03        0.2923  5.0138e-03     0.0527 -1.4977e-02              NaN               NaN                  NaN
2010-08-20   0.0964  0.0757  0.0314  45.2355 -0.0905          0.8         NaN   1.0000 -0.1298   3.3368e-01  1.6493e-02        0.3570  1.4809e-03     0.0477 -1.5823e-02              NaN               NaN                  NaN
2010-08-23   0.0961  0.0716  0.0690  52.3497 -0.0545          0.8         NaN   1.0000 -0.0829   4.4215e-01  5.3929e-02        0.5720  1.1724e-02     0.1243  6.7102e-03              NaN               NaN                  NaN
2010-08-24   0.0949  0.0741  0.0615  46.4790 -0.0835          0.6         NaN   1.0000 -0.1253   1.5019e-01 -4.6200e-02        0.3779  1.1419e-02     0.1343  9.9381e-03              NaN               NaN                  NaN
2010-08-25   0.0949  0.0715  0.0714  50.9391 -0.0316          0.8         NaN   1.0000 -0.0934   1.2883e-01  3.6461e-02        0.5240  1.2001e-02     0.0982  2.7737e-04              NaN               NaN                  NaN
2010-08-26   0.0913  0.0693  0.0339  49.9780 -0.0468          0.6         NaN   1.0000 -0.1002   6.3625e-02 -7.5377e-03        0.4927  5.5452e-03     0.0266 -5.8738e-03              NaN               NaN                  NaN
2010-08-27   0.0865  0.0659  0.0188  49.6411 -0.0319          0.4         NaN   1.0000 -0.1025  -2.5651e-02 -2.5367e-03        0.4822 -1.4945e-03    -0.0694 -1.3496e-02              NaN               NaN                  NaN
2010-08-30   0.0831  0.0627  0.0292  50.8524 -0.0035          0.4         NaN   1.0000 -0.0948  -2.9930e-02  8.6345e-03        0.5178  5.8500e-03     0.0016  3.0488e-04              NaN               NaN                  NaN
2010-08-31   0.0797  0.0614  0.0277  48.0016 -0.0688          0.4         NaN   1.0000 -0.1125  -4.2968e-02 -1.9628e-02        0.4363 -3.6605e-03    -0.0064 -2.1661e-03              NaN               NaN                  NaN
2010-09-01   0.0798  0.0585  0.0592  54.7896 -0.0683          0.4         NaN   1.0000 -0.0381  -2.7773e-01  4.9789e-02        0.7356  5.8424e-03     0.0711 -7.6845e-06              NaN               NaN                  NaN
2010-09-02   0.0785  0.0559  0.0442  58.4626 -0.0094          0.6         NaN   1.0000  0.0000  -3.9232e-01  2.9831e-02        0.9532  1.6229e-02     0.1305  1.9889e-02              NaN               NaN                  NaN
2010-09-03   0.0760  0.0541  0.0304  58.3784  0.0293          0.6         NaN   1.0000 -0.0005  -3.5783e-01 -4.7721e-04        0.9360  1.9335e-02     0.0664  1.3493e-02              NaN               NaN                  NaN
2010-09-07   0.0732  0.0534  0.0268  54.1215  0.0485          0.4         NaN   1.0000 -0.0247  -3.7086e-01 -2.4228e-02        0.8056  1.3488e-02     0.0243 -2.7406e-03              NaN               NaN                  NaN
2010-09-08   0.0699  0.0502  0.0196  56.5311  0.0663          0.6         NaN   1.0000 -0.0076  -4.1174e-01  1.7527e-02        0.8977  1.8529e-03    -0.0202 -1.7482e-02              NaN               NaN                  NaN
2010-09-09   0.0666  0.0482  0.0174  54.8933  0.0883          0.4         NaN   1.0000 -0.0166  -4.0509e-01 -9.0861e-03        0.8491 -4.0664e-03    -0.0619 -1.7554e-02              NaN               NaN                  NaN
2010-09-10   0.0674  0.0501  0.0580  50.4200  0.1268          0.2         NaN   1.0000 -0.0423  -3.6253e-01 -2.6074e-02        0.6896 -7.7151e-03    -0.0664 -9.5680e-03              NaN               NaN                  NaN
2010-09-13   0.0661  0.0478  0.0352  54.4874  0.1773          0.4         NaN   1.0000 -0.0161  -3.9549e-01  2.7263e-02        0.8092 -1.8097e-03    -0.0430  2.2567e-03              NaN               NaN                  NaN
2010-09-14   0.0665  0.0472  0.0507  57.2359  0.1528          0.6         NaN   1.0000  0.0000  -4.5121e-01  1.9307e-02        0.8532  2.1425e-03     0.0241  9.8577e-03              NaN               NaN                  NaN
2010-09-15   0.0675  0.0460  0.0551  62.4811  0.1704          0.6         NaN   1.0000  0.0000  -2.0491e-01  4.0717e-02        0.9945  1.6504e-02     0.1660  1.8314e-02              NaN               NaN                  NaN
2010-09-16   0.0737  0.0528  0.1108  53.8752  0.0935          0.6         NaN   1.0000 -0.0473  -2.3001e-01 -4.7314e-02        0.5404  1.3396e-02    -0.0298  1.1253e-02              NaN               NaN                  NaN
2010-09-17   0.0757  0.0561  0.0751  48.9213  0.0778          0.6         NaN   1.0000 -0.0796   1.4032e-02 -3.3904e-02        0.3699 -5.6415e-03    -0.3246 -2.2146e-02              NaN               NaN                  NaN
2010-09-20   0.0759  0.0541  0.0565  54.2208  0.1208          0.6         NaN   1.0000 -0.0419  -1.0523e-01  4.1026e-02        0.5435 -8.8651e-03    -0.3823 -2.2261e-02              NaN               NaN                  NaN
2010-09-21   0.0747  0.0540  0.0424  52.1838  0.0874          0.4         NaN   1.0000 -0.0550  -1.4762e-01 -1.3768e-02        0.4805 -1.0752e-02    -0.3533 -5.1108e-03              NaN               NaN                  NaN
2010-09-22   0.0748  0.0565  0.0579  46.3617 -0.0129          0.2         NaN   1.0000 -0.0960  -7.2149e-02 -4.3332e-02        0.2848 -7.8552e-03    -0.1817  1.0099e-03              NaN               NaN                  NaN
2010-09-23   0.0725  0.0556  0.0327  44.5189  0.0188          0.2         NaN   1.0000 -0.1101   5.8484e-02 -1.5604e-02        0.0600 -1.2553e-02    -0.2251 -1.8004e-03              NaN               NaN                  NaN
2010-09-24   0.0704  0.0525  0.0313  48.3682  0.0100          0.4         NaN   1.0000 -0.0855  -1.0264e-01  2.7607e-02        0.2010 -1.5334e-02    -0.2516 -7.4784e-03              NaN               NaN                  NaN
2010-09-27   0.0690  0.0504  0.0370  51.2678  0.0395          0.4         NaN   1.0000 -0.0660  -4.9385e-02  2.1396e-02        0.3133 -1.1739e-03    -0.0620  1.1379e-02              NaN               NaN                  NaN
2010-09-28   0.0686  0.0481  0.0449  56.5804  0.0863          0.6 -5.3779e-02   0.9978 -0.0264   2.7709e-02  4.2377e-02        0.5405  1.9676e-02     0.2201  3.5010e-02              NaN               NaN                  NaN
2010-09-29   0.0680  0.0464  0.0409  59.7316  0.1062          0.8 -4.5735e-02   0.9972  0.0000   1.1942e-01  2.7098e-02        0.6776  2.9596e-02     0.5852  3.0770e-02              NaN               NaN                  NaN
2010-09-30   0.0725  0.0533  0.0960  49.3003  0.0477          0.8 -4.3877e-02   0.9805 -0.0714   7.7339e-03 -7.1424e-02        0.2486  9.8856e-03     0.3291 -9.7906e-03              NaN               NaN                  NaN
2010-10-01   0.0694  0.0505  0.0214  50.4280  0.0073          0.8  1.3553e-03   0.8727 -0.0628  -4.0266e-02  9.3042e-03        0.3005 -4.0568e-03     0.1528 -3.3653e-02              NaN               NaN                  NaN
2010-10-04   0.0686  0.0490  0.0414  52.7524 -0.0033          0.8  8.8253e-02   0.9434 -0.0450   2.7695e-03  1.8932e-02        0.4071 -1.0354e-02     0.0321 -2.0240e-02              NaN               NaN                  NaN
2010-10-05   0.0651  0.0462  0.0137  53.5348  0.0033          0.8  1.0651e-01   1.1117 -0.0391  -1.7538e-02  6.1958e-03        0.4426 -5.1804e-03     0.0364 -1.1236e-03              NaN               NaN                  NaN
2010-10-06   0.0649  0.0476  0.0459  49.0918 -0.0039          0.6  5.1668e-02   1.0154 -0.0692  -6.9956e-02 -3.1250e-02        0.2623  2.9820e-03     0.2693  1.3336e-02              NaN               NaN                  NaN
2010-10-07   0.0617  0.0453  0.0147  48.8932 -0.0225          0.6  5.6828e-02   1.0267 -0.0705   3.7270e-02 -1.4663e-03        0.2541 -4.2140e-03     0.0693  9.6636e-04              NaN               NaN                  NaN
2010-10-08   0.0592  0.0434  0.0196  48.8932 -0.0135          0.4  6.4307e-02   1.0202 -0.0705  -6.0824e-02  0.0000e+00        0.2541 -8.7295e-03    -0.0774 -1.1712e-02              NaN               NaN                  NaN
2010-10-11   0.0580  0.0429  0.0311  47.4816  0.0035          0.2  3.6463e-02   0.9309 -0.0792   3.7680e-02 -9.3025e-03        0.2022 -8.6592e-03    -0.1432 -4.4451e-03              NaN               NaN                  NaN
2010-10-12   0.0550  0.0408  0.0124  47.4816 -0.0232          0.0 -1.1675e-02   0.9460 -0.0792   7.8792e-02  0.0000e+00        0.2022 -3.0973e-03    -0.0867  5.6322e-03              NaN               NaN                  NaN
2010-10-13   0.0540  0.0394  0.0297  50.1180 -0.0275          0.2 -9.1523e-03   0.9533 -0.0655   4.1983e-02  1.4822e-02        0.2841  1.3887e-04     0.0244  8.7980e-03              NaN               NaN                  NaN
2010-10-14   0.0531  0.0384  0.0304  51.9368 -0.0560          0.4 -3.7341e-02   1.2306 -0.0560  -2.3981e-02  1.0224e-02        0.4717  4.5792e-03     0.1642  7.6765e-03              NaN               NaN                  NaN
2010-10-15   0.0524  0.0383  0.0316  49.9745 -0.0191          0.4 -7.6594e-02   1.1928 -0.0655   1.2141e-02 -1.0121e-02        0.3924  5.4312e-03     0.1616  5.2924e-03              NaN               NaN                  NaN
2010-10-18   0.0507  0.0376  0.0208  47.1436  0.0000          0.4 -4.3289e-02   1.3095 -0.0796  -1.8269e-02 -1.5088e-02        0.2755 -9.7850e-05     0.0323 -4.6771e-03              NaN               NaN                  NaN
2010-10-19   0.0490  0.0367  0.0205  45.5304 -0.0480          0.4 -4.6256e-02   1.3203 -0.0878  -1.1489e-01 -8.8977e-03        0.2076 -7.3655e-03    -0.1874 -1.2797e-02              NaN               NaN                  NaN
2010-10-20   0.0486  0.0353  0.0315  51.4894 -0.0058          0.4 -4.3822e-02   1.3088 -0.0605  -3.2934e-01  2.9925e-02        0.4340 -3.3792e-03    -0.1679 -3.2814e-03              NaN               NaN                  NaN
2010-10-21   0.0475  0.0343  0.0241  52.4227  0.0443          0.4 -4.5338e-02   1.3044 -0.0560  -4.6473e-02  4.8378e-03        0.4400  4.0893e-03     0.1133  1.1455e-02              NaN               NaN                  NaN
2010-10-22   0.0459  0.0333  0.0183  52.0986  0.0593          0.4 -3.1672e-02   1.3487 -0.0573   1.0912e-01 -1.4458e-03        0.3349  8.2168e-03     0.2119  1.1596e-02              NaN               NaN                  NaN
2010-10-25   0.0439  0.0316  0.0125  53.4426  0.0373          0.6 -1.8187e-02   1.3461 -0.0514   5.7473e-02  6.2766e-03        0.3954  8.1624e-03     0.2504  4.0731e-03              NaN               NaN                  NaN
2010-10-26   0.0472  0.0332  0.0637  58.3748  0.0404          0.8 -1.2300e-02   1.3651 -0.0282   6.7925e-02  2.4460e-02        0.6326  7.2415e-03     0.3183 -9.7533e-04              NaN               NaN                  NaN
2010-10-27   0.0473  0.0338  0.0348  54.0241 -0.0187          0.6 -1.2909e-02   1.3627 -0.0446  -1.3230e-02 -1.6854e-02        0.4651  5.4380e-03     0.2061 -2.7244e-03              NaN               NaN                  NaN
2010-10-28   0.0465  0.0329  0.0255  55.8930 -0.0359          0.6  4.6059e-03   1.3561 -0.0080  -1.0751e-01  9.0500e-03        0.6364  5.2038e-03     0.2529 -2.0377e-03              NaN               NaN                  NaN
2010-10-29   0.0470  0.0323  0.0366  61.6365  0.0701          0.8  6.6248e-03   1.2786  0.0000  -3.6603e-02  3.0672e-02        0.9840  8.4790e-03     0.2374  3.0410e-03              NaN               NaN                  NaN